version 2:

sources:
   
  - name: landing
    database: landing
    schema: raw 
    tables:
    - name: stg_kyiv_data
    - name: stg_paris_data
    - name: stg_munich_data
    - name: stg_zagreb_data
    - name: stg_oslo_data



